package com.chilioil.autoimport.bean;

import java.io.Serializable;
import java.util.Date;

public class TImgUrl implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_url.id
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_url.k
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    private String k;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_url.v
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    private String v;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_url.enable_falg
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    private Boolean enableFalg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_url.create_user
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_url.create_datetime
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    private Date createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_url.lastupdate_user
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    private String lastupdateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_img_url.lastupdate_datetime
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    private Date lastupdateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_img_url
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_url.id
     *
     * @return the value of t_img_url.id
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_url.id
     *
     * @param id the value for t_img_url.id
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_url.k
     *
     * @return the value of t_img_url.k
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public String getK() {
        return k;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_url.k
     *
     * @param k the value for t_img_url.k
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public void setK(String k) {
        this.k = k;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_url.v
     *
     * @return the value of t_img_url.v
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public String getV() {
        return v;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_url.v
     *
     * @param v the value for t_img_url.v
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public void setV(String v) {
        this.v = v;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_url.enable_falg
     *
     * @return the value of t_img_url.enable_falg
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public Boolean getEnableFalg() {
        return enableFalg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_url.enable_falg
     *
     * @param enableFalg the value for t_img_url.enable_falg
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public void setEnableFalg(Boolean enableFalg) {
        this.enableFalg = enableFalg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_url.create_user
     *
     * @return the value of t_img_url.create_user
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_url.create_user
     *
     * @param createUser the value for t_img_url.create_user
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_url.create_datetime
     *
     * @return the value of t_img_url.create_datetime
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_url.create_datetime
     *
     * @param createDatetime the value for t_img_url.create_datetime
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_url.lastupdate_user
     *
     * @return the value of t_img_url.lastupdate_user
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public String getLastupdateUser() {
        return lastupdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_url.lastupdate_user
     *
     * @param lastupdateUser the value for t_img_url.lastupdate_user
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public void setLastupdateUser(String lastupdateUser) {
        this.lastupdateUser = lastupdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_img_url.lastupdate_datetime
     *
     * @return the value of t_img_url.lastupdate_datetime
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public Date getLastupdateDatetime() {
        return lastupdateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_img_url.lastupdate_datetime
     *
     * @param lastupdateDatetime the value for t_img_url.lastupdate_datetime
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public void setLastupdateDatetime(Date lastupdateDatetime) {
        this.lastupdateDatetime = lastupdateDatetime;
    }
}