package com.chilioil.autoimport.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TImgUrlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_img_url
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_img_url
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_img_url
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_url
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public TImgUrlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_url
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_url
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_url
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_url
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_url
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_url
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_url
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_url
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_url
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_img_url
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_img_url
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andKIsNull() {
            addCriterion("k is null");
            return (Criteria) this;
        }

        public Criteria andKIsNotNull() {
            addCriterion("k is not null");
            return (Criteria) this;
        }

        public Criteria andKEqualTo(String value) {
            addCriterion("k =", value, "k");
            return (Criteria) this;
        }

        public Criteria andKNotEqualTo(String value) {
            addCriterion("k <>", value, "k");
            return (Criteria) this;
        }

        public Criteria andKGreaterThan(String value) {
            addCriterion("k >", value, "k");
            return (Criteria) this;
        }

        public Criteria andKGreaterThanOrEqualTo(String value) {
            addCriterion("k >=", value, "k");
            return (Criteria) this;
        }

        public Criteria andKLessThan(String value) {
            addCriterion("k <", value, "k");
            return (Criteria) this;
        }

        public Criteria andKLessThanOrEqualTo(String value) {
            addCriterion("k <=", value, "k");
            return (Criteria) this;
        }

        public Criteria andKLike(String value) {
            addCriterion("k like", value, "k");
            return (Criteria) this;
        }

        public Criteria andKNotLike(String value) {
            addCriterion("k not like", value, "k");
            return (Criteria) this;
        }

        public Criteria andKIn(List<String> values) {
            addCriterion("k in", values, "k");
            return (Criteria) this;
        }

        public Criteria andKNotIn(List<String> values) {
            addCriterion("k not in", values, "k");
            return (Criteria) this;
        }

        public Criteria andKBetween(String value1, String value2) {
            addCriterion("k between", value1, value2, "k");
            return (Criteria) this;
        }

        public Criteria andKNotBetween(String value1, String value2) {
            addCriterion("k not between", value1, value2, "k");
            return (Criteria) this;
        }

        public Criteria andVIsNull() {
            addCriterion("v is null");
            return (Criteria) this;
        }

        public Criteria andVIsNotNull() {
            addCriterion("v is not null");
            return (Criteria) this;
        }

        public Criteria andVEqualTo(String value) {
            addCriterion("v =", value, "v");
            return (Criteria) this;
        }

        public Criteria andVNotEqualTo(String value) {
            addCriterion("v <>", value, "v");
            return (Criteria) this;
        }

        public Criteria andVGreaterThan(String value) {
            addCriterion("v >", value, "v");
            return (Criteria) this;
        }

        public Criteria andVGreaterThanOrEqualTo(String value) {
            addCriterion("v >=", value, "v");
            return (Criteria) this;
        }

        public Criteria andVLessThan(String value) {
            addCriterion("v <", value, "v");
            return (Criteria) this;
        }

        public Criteria andVLessThanOrEqualTo(String value) {
            addCriterion("v <=", value, "v");
            return (Criteria) this;
        }

        public Criteria andVLike(String value) {
            addCriterion("v like", value, "v");
            return (Criteria) this;
        }

        public Criteria andVNotLike(String value) {
            addCriterion("v not like", value, "v");
            return (Criteria) this;
        }

        public Criteria andVIn(List<String> values) {
            addCriterion("v in", values, "v");
            return (Criteria) this;
        }

        public Criteria andVNotIn(List<String> values) {
            addCriterion("v not in", values, "v");
            return (Criteria) this;
        }

        public Criteria andVBetween(String value1, String value2) {
            addCriterion("v between", value1, value2, "v");
            return (Criteria) this;
        }

        public Criteria andVNotBetween(String value1, String value2) {
            addCriterion("v not between", value1, value2, "v");
            return (Criteria) this;
        }

        public Criteria andEnableFalgIsNull() {
            addCriterion("enable_falg is null");
            return (Criteria) this;
        }

        public Criteria andEnableFalgIsNotNull() {
            addCriterion("enable_falg is not null");
            return (Criteria) this;
        }

        public Criteria andEnableFalgEqualTo(Boolean value) {
            addCriterion("enable_falg =", value, "enableFalg");
            return (Criteria) this;
        }

        public Criteria andEnableFalgNotEqualTo(Boolean value) {
            addCriterion("enable_falg <>", value, "enableFalg");
            return (Criteria) this;
        }

        public Criteria andEnableFalgGreaterThan(Boolean value) {
            addCriterion("enable_falg >", value, "enableFalg");
            return (Criteria) this;
        }

        public Criteria andEnableFalgGreaterThanOrEqualTo(Boolean value) {
            addCriterion("enable_falg >=", value, "enableFalg");
            return (Criteria) this;
        }

        public Criteria andEnableFalgLessThan(Boolean value) {
            addCriterion("enable_falg <", value, "enableFalg");
            return (Criteria) this;
        }

        public Criteria andEnableFalgLessThanOrEqualTo(Boolean value) {
            addCriterion("enable_falg <=", value, "enableFalg");
            return (Criteria) this;
        }

        public Criteria andEnableFalgIn(List<Boolean> values) {
            addCriterion("enable_falg in", values, "enableFalg");
            return (Criteria) this;
        }

        public Criteria andEnableFalgNotIn(List<Boolean> values) {
            addCriterion("enable_falg not in", values, "enableFalg");
            return (Criteria) this;
        }

        public Criteria andEnableFalgBetween(Boolean value1, Boolean value2) {
            addCriterion("enable_falg between", value1, value2, "enableFalg");
            return (Criteria) this;
        }

        public Criteria andEnableFalgNotBetween(Boolean value1, Boolean value2) {
            addCriterion("enable_falg not between", value1, value2, "enableFalg");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNull() {
            addCriterion("create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNotNull() {
            addCriterion("create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeEqualTo(Date value) {
            addCriterion("create_datetime =", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotEqualTo(Date value) {
            addCriterion("create_datetime <>", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThan(Date value) {
            addCriterion("create_datetime >", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_datetime >=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThan(Date value) {
            addCriterion("create_datetime <", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("create_datetime <=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIn(List<Date> values) {
            addCriterion("create_datetime in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotIn(List<Date> values) {
            addCriterion("create_datetime not in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeBetween(Date value1, Date value2) {
            addCriterion("create_datetime between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("create_datetime not between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdateUserIsNull() {
            addCriterion("lastupdate_user is null");
            return (Criteria) this;
        }

        public Criteria andLastupdateUserIsNotNull() {
            addCriterion("lastupdate_user is not null");
            return (Criteria) this;
        }

        public Criteria andLastupdateUserEqualTo(String value) {
            addCriterion("lastupdate_user =", value, "lastupdateUser");
            return (Criteria) this;
        }

        public Criteria andLastupdateUserNotEqualTo(String value) {
            addCriterion("lastupdate_user <>", value, "lastupdateUser");
            return (Criteria) this;
        }

        public Criteria andLastupdateUserGreaterThan(String value) {
            addCriterion("lastupdate_user >", value, "lastupdateUser");
            return (Criteria) this;
        }

        public Criteria andLastupdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("lastupdate_user >=", value, "lastupdateUser");
            return (Criteria) this;
        }

        public Criteria andLastupdateUserLessThan(String value) {
            addCriterion("lastupdate_user <", value, "lastupdateUser");
            return (Criteria) this;
        }

        public Criteria andLastupdateUserLessThanOrEqualTo(String value) {
            addCriterion("lastupdate_user <=", value, "lastupdateUser");
            return (Criteria) this;
        }

        public Criteria andLastupdateUserLike(String value) {
            addCriterion("lastupdate_user like", value, "lastupdateUser");
            return (Criteria) this;
        }

        public Criteria andLastupdateUserNotLike(String value) {
            addCriterion("lastupdate_user not like", value, "lastupdateUser");
            return (Criteria) this;
        }

        public Criteria andLastupdateUserIn(List<String> values) {
            addCriterion("lastupdate_user in", values, "lastupdateUser");
            return (Criteria) this;
        }

        public Criteria andLastupdateUserNotIn(List<String> values) {
            addCriterion("lastupdate_user not in", values, "lastupdateUser");
            return (Criteria) this;
        }

        public Criteria andLastupdateUserBetween(String value1, String value2) {
            addCriterion("lastupdate_user between", value1, value2, "lastupdateUser");
            return (Criteria) this;
        }

        public Criteria andLastupdateUserNotBetween(String value1, String value2) {
            addCriterion("lastupdate_user not between", value1, value2, "lastupdateUser");
            return (Criteria) this;
        }

        public Criteria andLastupdateDatetimeIsNull() {
            addCriterion("lastupdate_datetime is null");
            return (Criteria) this;
        }

        public Criteria andLastupdateDatetimeIsNotNull() {
            addCriterion("lastupdate_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andLastupdateDatetimeEqualTo(Date value) {
            addCriterion("lastupdate_datetime =", value, "lastupdateDatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdateDatetimeNotEqualTo(Date value) {
            addCriterion("lastupdate_datetime <>", value, "lastupdateDatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdateDatetimeGreaterThan(Date value) {
            addCriterion("lastupdate_datetime >", value, "lastupdateDatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdateDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("lastupdate_datetime >=", value, "lastupdateDatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdateDatetimeLessThan(Date value) {
            addCriterion("lastupdate_datetime <", value, "lastupdateDatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdateDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("lastupdate_datetime <=", value, "lastupdateDatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdateDatetimeIn(List<Date> values) {
            addCriterion("lastupdate_datetime in", values, "lastupdateDatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdateDatetimeNotIn(List<Date> values) {
            addCriterion("lastupdate_datetime not in", values, "lastupdateDatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdateDatetimeBetween(Date value1, Date value2) {
            addCriterion("lastupdate_datetime between", value1, value2, "lastupdateDatetime");
            return (Criteria) this;
        }

        public Criteria andLastupdateDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("lastupdate_datetime not between", value1, value2, "lastupdateDatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_img_url
     *
     * @mbg.generated do_not_delete_during_merge Sat Jul 11 17:57:21 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_img_url
     *
     * @mbg.generated Sat Jul 11 17:57:21 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}